### ISSUE TITLE
No UTF-8 support

### ISSUE THREAD

**Issue by fomalsd** [ndo360/JParanoiaRPG#25]
When sending UTF-8 special chars, the receiving side only sees questionmarks.

**Comment by ndo360** [comment]
This issue, while partially fixed, doesn't fully fix the UTF-8 issue.

Logs, Character Sheets, and possibly more... all do not still support UTF-8.

**Comment by ndo360** [comment]
Resolved fully now, will reopen if it turns out it still isn't fixed.
